services:
  app:
    build: .
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    container_name: secret_santa_app

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - app
    container_name: secret_santa_nginx

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: secretsanta
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: secret_santa_db

  bot:
    build: .
    command: php artisan telegram:run
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - app
      - db
    container_name: secret_santa_bot

volumes:
  db_data:
